Repository Capston-Leap/backend, pull requests merged in 2025-05, with the labels that each got.

#67 Feat #66 마이페이지 - 본인이 작성한 커뮤니티 게시글 목록 조회
  src/main/java/com/dash/leap/domain/community/controller/PostController.java
  src/main/java/com/dash/leap/domain/community/controller/docs/PostControllerDocs.java
  src/main/java/com/dash/leap/domain/community/repository/PostRepository.java
  src/main/java/com/dash/leap/domain/community/service/PostService.java
Labels: feature

#71 Refactor #68 커뮤니티 예외 처리 보완
  src/main/java/com/dash/leap/domain/community/exception/BadRequestException.java
  src/main/java/com/dash/leap/domain/community/exception/CommunityExceptionHandler.java
  src/main/java/com/dash/leap/domain/community/exception/ForbiddenException.java
  src/main/java/com/dash/leap/domain/community/service/CommentService.java
  src/main/java/com/dash/leap/domain/community/service/PostService.java
Labels: refactor

#73 Refactor #72 예외 처리 범위 및 메시지 개선
  src/main/java/com/dash/leap/domain/community/exception/CommunityExceptionHandler.java
  src/main/java/com/dash/leap/domain/community/service/CommentService.java
  src/main/java/com/dash/leap/domain/community/service/PostService.java
  src/main/java/com/dash/leap/domain/diary/exception/DiaryExceptionHandler.java
  src/main/java/com/dash/leap/domain/diary/service/DiaryService.java
Labels: refactor

#76 Fix #74 회원탈퇴 로직 수정
  src/main/java/com/dash/leap/domain/user/entity/User.java
  src/main/java/com/dash/leap/domain/user/service/UserService.java
  src/main/java/com/dash/leap/global/auth/jwt/service/JwtAuthenticationFilter.java
  src/main/java/com/dash/leap/global/auth/user/CustomUserService.java
  src/main/java/com/dash/leap/global/config/security/SecurityConfig.java
Labels: fix

#79 Feature #77 관리자 기본 기능
  src/main/java/com/dash/leap/admin/user/controller/AdminAuthController.java
  src/main/java/com/dash/leap/admin/user/controller/docs/AdminAuthControllerDocs.java
  src/main/java/com/dash/leap/admin/user/dto/request/AdminRegisterRequest.java
  src/main/java/com/dash/leap/admin/user/dto/response/AdminRegisterResponse.java
  src/main/java/com/dash/leap/admin/user/service/AdminAuthService.java
  src/main/java/com/dash/leap/domain/user/controller/UserController.java
  src/main/java/com/dash/leap/domain/user/controller/docs/UserControllerDocs.java
  src/main/java/com/dash/leap/domain/user/service/UserService.java
  src/main/java/com/dash/leap/global/auth/dto/request/LoginRequest.java
  src/main/java/com/dash/leap/global/auth/dto/response/LoginResponse.java
  src/main/java/com/dash/leap/global/auth/jwt/service/JwtAuthenticationFilter.java
  src/main/java/com/dash/leap/global/auth/jwt/service/JwtTokenProvider.java
  src/main/java/com/dash/leap/global/config/security/SecurityConfig.java
  src/main/java/com/dash/leap/global/config/swagger/SwaggerConfig.java
Labels: feature

#82 Feature #80 관리자 회원 관리
  src/main/java/com/dash/leap/admin/user/controller/AdminUserController.java
  src/main/java/com/dash/leap/admin/user/controller/docs/AdminUserControllerDocs.java
  src/main/java/com/dash/leap/admin/user/dto/response/AdminUserListResponse.java
  src/main/java/com/dash/leap/admin/user/dto/response/AdminUserResponse.java
  src/main/java/com/dash/leap/admin/user/exception/AdminUserExceptionHandler.java
  src/main/java/com/dash/leap/admin/user/exception/AlreadyDeletedException.java
  src/main/java/com/dash/leap/admin/user/service/AdminUserService.java
Labels: feature

#83 Feature #81 Admin 커뮤니티 관리 기능
  src/main/java/com/dash/leap/admin/community/controller/AdminCommunityController.java
  src/main/java/com/dash/leap/admin/community/controller/docs/AdminCommunityControllerDocs.java
  src/main/java/com/dash/leap/admin/community/dto/response/CategoryListResponse.java
  src/main/java/com/dash/leap/admin/community/dto/response/PostDetailResponse.java
  src/main/java/com/dash/leap/admin/community/dto/response/PostListAllResponse.java
  src/main/java/com/dash/leap/admin/community/exception/AdminCommunityExceptionHandler.java
  src/main/java/com/dash/leap/admin/community/exception/BadRequestException.java
  src/main/java/com/dash/leap/admin/community/exception/ForbiddenException.java
  src/main/java/com/dash/leap/admin/community/service/AdminCommunityService.java
  src/main/java/com/dash/leap/domain/community/controller/CommentController.java
  src/main/java/com/dash/leap/domain/community/controller/PostController.java
Labels: feature

#88 Feature #85 Admin 자립지원정보 관리 기능
  src/main/java/com/dash/leap/admin/information/controller/AdminInformationController.java
  src/main/java/com/dash/leap/admin/information/controller/docs/AdminInformationControllerDocs.java
  src/main/java/com/dash/leap/admin/information/dto/request/InformationCreateRequest.java
  src/main/java/com/dash/leap/admin/information/dto/request/InformationUpdateRequest.java
  src/main/java/com/dash/leap/admin/information/dto/response/InformationCreateResponse.java
  src/main/java/com/dash/leap/admin/information/dto/response/InformationDeleteResponse.java
  src/main/java/com/dash/leap/admin/information/dto/response/InformationDetailResponse.java
  src/main/java/com/dash/leap/admin/information/dto/response/InformationListResponse.java
  src/main/java/com/dash/leap/admin/information/dto/response/InformationUpdateResponse.java
  src/main/java/com/dash/leap/admin/information/exception/AdminInformationExceptionHandler.java
  src/main/java/com/dash/leap/admin/information/exception/ForbiddenException.java
  src/main/java/com/dash/leap/admin/information/service/AdminInformationService.java
  src/main/java/com/dash/leap/domain/information/entity/Information.java
Labels: feature

#91 Refactor #89 커뮤니티 게시글 및 댓글 삭제 응답 메시지 추가
  src/main/java/com/dash/leap/admin/community/controller/AdminCommunityController.java
  src/main/java/com/dash/leap/admin/community/controller/docs/AdminCommunityControllerDocs.java
  src/main/java/com/dash/leap/admin/community/dto/response/CommentDeleteResponse.java
  src/main/java/com/dash/leap/admin/community/dto/response/PostDeleteResponse.java
  src/main/java/com/dash/leap/admin/community/service/AdminCommunityService.java
  src/main/java/com/dash/leap/domain/community/controller/CommentController.java
  src/main/java/com/dash/leap/domain/community/controller/PostController.java
  src/main/java/com/dash/leap/domain/community/controller/docs/CommentControllerDocs.java
  src/main/java/com/dash/leap/domain/community/controller/docs/PostControllerDocs.java
  src/main/java/com/dash/leap/domain/community/dto/response/CommentDeleteResponse.java
  src/main/java/com/dash/leap/domain/community/dto/response/PostDeleteResponse.java
  src/main/java/com/dash/leap/domain/community/service/CommentService.java
  src/main/java/com/dash/leap/domain/community/service/PostService.java
Labels: refactor

#92 Feature #87 Admin 대시보드
  src/main/java/com/dash/leap/admin/user/controller/AdminDashboardController.java
  src/main/java/com/dash/leap/admin/user/controller/docs/AdminDashboardControllerDocs.java
  src/main/java/com/dash/leap/admin/user/dto/response/AdminDashboardResponse.java
  src/main/java/com/dash/leap/admin/user/service/AdminDashboardService.java
  src/main/java/com/dash/leap/domain/user/repository/UserRepository.java
Labels: feature

#93 Feature #90 AI 연동
  .gitignore
  ai/emotion/sa_load.py
  ai/emotion/sa_result_1.py
  ai/summary/kobart_summary/config.json
  ai/summary/kobart_summary/generation_config.json
  ai/summary/sm_load.py
  ai/summary/sm_result_1.py
  src/main/java/com/dash/leap/domain/diary/controller/DiaryController.java
  src/main/java/com/dash/leap/domain/diary/dto/response/DiaryCalendarResponse.java
  src/main/java/com/dash/leap/domain/diary/dto/response/DiaryCreateResponse.java
  src/main/java/com/dash/leap/domain/diary/dto/response/DiaryDetailResponse.java
  src/main/java/com/dash/leap/domain/diary/entity/DiaryAnalysis.java
  src/main/java/com/dash/leap/domain/diary/repository/EmotionRepository.java
  src/main/java/com/dash/leap/domain/diary/service/DiaryService.java
  src/main/java/com/dash/leap/global/aimodel/converter/EmotionScoresConverter.java
  src/main/java/com/dash/leap/global/aimodel/exception/AIModelRunExceptionHandler.java
  src/main/java/com/dash/leap/global/aimodel/exception/EmotionScoreConvertException.java
  src/main/java/com/dash/leap/global/aimodel/exception/TextSummaryFailedException.java
  src/main/java/com/dash/leap/global/aimodel/service/EmotionAnalysisService.java
  src/main/java/com/dash/leap/global/aimodel/service/SummaryService.java
Labels: feature

#95 Feature #94 home and fix error
  src/main/java/com/dash/leap/admin/user/service/AdminUserService.java
  src/main/java/com/dash/leap/domain/home/controller/HomeController.java
  src/main/java/com/dash/leap/domain/home/controller/docs/HomeControllerDocs.java
  src/main/java/com/dash/leap/domain/home/dto/response/HomeResponse.java
  src/main/java/com/dash/leap/domain/home/service/HomeService.java
  src/main/java/com/dash/leap/domain/information/repository/InformationRepository.java
  src/main/java/com/dash/leap/domain/mission/service/MissionService.java
  src/main/java/com/dash/leap/domain/user/entity/User.java
  src/main/java/com/dash/leap/domain/user/service/UserService.java
Labels: fix, feature

#102 Feature /user/me API 추가
  src/main/java/com/dash/leap/domain/user/controller/UserController.java
  src/main/java/com/dash/leap/domain/user/controller/docs/UserControllerDocs.java
  src/main/java/com/dash/leap/domain/user/dto/response/MyPageResponse.java
  src/main/java/com/dash/leap/domain/user/dto/response/UserResponse.java
  src/main/java/com/dash/leap/domain/user/service/UserService.java
Labels: feature

#103 Fix cors 설정에 PATCH 추가 하여 오류 cors 오류 해결
  src/main/java/com/dash/leap/global/config/security/SecurityConfig.java
Labels: fix

#104 Chore: 각 service 코드에 log 추가
  src/main/java/com/dash/leap/admin/community/service/AdminCommunityService.java
  src/main/java/com/dash/leap/admin/information/service/AdminInformationService.java
  src/main/java/com/dash/leap/admin/mission/service/AdminMissionService.java
  src/main/java/com/dash/leap/admin/user/service/AdminAuthService.java
  src/main/java/com/dash/leap/admin/user/service/AdminDashboardService.java
  src/main/java/com/dash/leap/admin/user/service/AdminUserService.java
  src/main/java/com/dash/leap/domain/chat/service/ChatMessageService.java
  src/main/java/com/dash/leap/domain/community/service/CommentService.java
  src/main/java/com/dash/leap/domain/community/service/PostService.java
  src/main/java/com/dash/leap/domain/diary/service/DiaryService.java
  src/main/java/com/dash/leap/domain/home/service/HomeService.java
  src/main/java/com/dash/leap/domain/information/service/InformationService.java
  src/main/java/com/dash/leap/domain/mission/service/MissionService.java
  src/main/java/com/dash/leap/domain/user/service/UserService.java
  src/main/java/com/dash/leap/global/aimodel/service/EmotionAnalysisService.java
  src/main/java/com/dash/leap/global/aimodel/service/SummaryService.java
  src/main/java/com/dash/leap/global/auth/jwt/service/AuthService.java
  src/main/java/com/dash/leap/global/auth/user/CustomUserService.java
Labels: chore

#105 Feature 페이징 관련 에러 검증 추가 및 global handler에서 handle
  src/main/java/com/dash/leap/admin/community/controller/AdminCommunityController.java
  src/main/java/com/dash/leap/admin/information/controller/AdminInformationController.java
  src/main/java/com/dash/leap/admin/mission/controller/AdminMissionController.java
  src/main/java/com/dash/leap/admin/user/controller/AdminAuthController.java
  src/main/java/com/dash/leap/admin/user/controller/AdminUserController.java
  src/main/java/com/dash/leap/domain/chat/controller/ChatMessageController.java
  src/main/java/com/dash/leap/domain/community/controller/PostController.java
  src/main/java/com/dash/leap/domain/information/controller/InformationController.java
  src/main/java/com/dash/leap/domain/mission/controller/MissionController.java
  src/main/java/com/dash/leap/global/exception/GlobalExceptionHandler.java
Labels: feature

#106 Fix gpt 응답 시 이모지 추출 로직 추가
  src/main/java/com/dash/leap/domain/chat/service/ChatMessageService.java
  src/main/java/com/dash/leap/domain/chat/service/prompt/SystemPromptFactory.java
Labels: fix

#107 Feature: 완료된 미션영역 API
  src/main/java/com/dash/leap/domain/mission/controller/MissionController.java
  src/main/java/com/dash/leap/domain/mission/controller/docs/MissionControllerDocs.java
  src/main/java/com/dash/leap/domain/mission/dto/response/CompletedMissionAreaResponse.java
  src/main/java/com/dash/leap/domain/mission/service/MissionService.java
  src/main/java/com/dash/leap/global/auth/user/CustomUserService.java
Labels: feature

#108 Chore: 코드 정리
  src/main/java/com/dash/leap/admin/information/controller/docs/AdminInformationControllerDocs.java
  src/main/java/com/dash/leap/admin/user/service/AdminAuthService.java
  src/main/java/com/dash/leap/domain/chat/entity/ChatAnalysis.java
  src/main/java/com/dash/leap/domain/user/dto/request/UserRegisterRequest.java
  src/main/java/com/dash/leap/domain/user/service/UserService.java
  src/main/java/com/dash/leap/global/auth/jwt/service/JwtTokenProvider.java
  src/main/java/com/dash/leap/global/exception/GlobalExceptionHandler.java
Labels: chore

#109 Fix: validation 제거
  src/main/java/com/dash/leap/domain/community/controller/PostController.java
Labels: fix

#110 Fix: InformationListResponse에 url 추가
  src/main/java/com/dash/leap/admin/information/dto/response/InformationListResponse.java
  src/main/java/com/dash/leap/admin/information/service/AdminInformationService.java
Labels: fix

#111 Fix: InformationDetailResponse에 content 추가
  src/main/java/com/dash/leap/admin/information/dto/response/InformationListResponse.java
  src/main/java/com/dash/leap/admin/information/service/AdminInformationService.java
Labels: fix
