Repository Capston-Leap/backend, pull requests merged in 2025-04, with the labels that each got.

#2 Feature #1 자립지원정보 조회
  src/main/java/com/dash/leap/domain/information/controller/InformationController.java
  src/main/java/com/dash/leap/domain/information/controller/docs/InformationControllerDocs.java
  src/main/java/com/dash/leap/domain/information/dto/response/InformationListResponse.java
  src/main/java/com/dash/leap/domain/information/dto/response/InformationResponse.java
  src/main/java/com/dash/leap/domain/information/entity/Information.java
  src/main/java/com/dash/leap/domain/information/entity/enums/InfoType.java
  src/main/java/com/dash/leap/domain/information/repository/InformationRepository.java
  src/main/java/com/dash/leap/domain/information/service/InformationService.java
Labels: feature

#4 Feature #3 회원가입
  build.gradle
  src/main/java/com/dash/leap/domain/community/entity/Comment.java
  src/main/java/com/dash/leap/domain/community/entity/Post.java
  src/main/java/com/dash/leap/domain/diary/entity/Diary.java
  src/main/java/com/dash/leap/domain/information/entity/Information.java
  src/main/java/com/dash/leap/domain/mission/entity/Mission.java
  src/main/java/com/dash/leap/domain/user/controller/UserController.java
  src/main/java/com/dash/leap/domain/user/controller/docs/UserControllerDocs.java
  src/main/java/com/dash/leap/domain/user/dto/request/IdDuplicateRequest.java
  src/main/java/com/dash/leap/domain/user/dto/request/UserRegisterRequest.java
  src/main/java/com/dash/leap/domain/user/dto/response/UserRegisterResponse.java
  src/main/java/com/dash/leap/domain/user/entity/User.java
  src/main/java/com/dash/leap/domain/user/repository/UserRepository.java
  src/main/java/com/dash/leap/domain/user/service/UserService.java
  src/main/java/com/dash/leap/global/auth/jwt/controller/AuthController.java
  src/main/java/com/dash/leap/global/auth/jwt/controller/docs/AuthControllerDocs.java
  src/main/java/com/dash/leap/global/auth/jwt/exception/DuplicateLoginIdException.java
  src/main/java/com/dash/leap/global/auth/jwt/service/AuthService.java
  src/main/java/com/dash/leap/global/config/security/SecurityConfig.java
  src/main/java/com/dash/leap/global/config/swagger/SwaggerConfig.java
  src/main/java/com/dash/leap/global/domain/BaseEntity.java
  src/main/java/com/dash/leap/global/exception/BaseException.java
Labels: feature

#7 Fix #6 user register exception
  build.gradle
  src/main/java/com/dash/leap/domain/user/controller/UserController.java
  src/main/java/com/dash/leap/global/auth/dto/request/IdDuplicateRequest.java
  src/main/java/com/dash/leap/global/auth/dto/response/IdDuplicateResponse.java
  src/main/java/com/dash/leap/global/auth/jwt/controller/AuthController.java
  src/main/java/com/dash/leap/global/auth/jwt/controller/docs/AuthControllerDocs.java
  src/main/java/com/dash/leap/global/auth/jwt/exception/DuplicateLoginIdException.java
  src/main/java/com/dash/leap/global/auth/jwt/exception/ExceptionResponse.java
  src/main/java/com/dash/leap/global/auth/jwt/exception/GlobalExceptionHandler.java
  src/main/java/com/dash/leap/global/auth/jwt/service/AuthService.java
Labels: fix

#11 Fix #10 swagger config
  src/main/java/com/dash/leap/global/auth/jwt/service/JwtAuthenticationFilter.java
  src/main/java/com/dash/leap/global/config/swagger/SwaggerConfig.java
  src/main/java/com/dash/leap/global/exception/ExceptionResponse.java
  src/main/java/com/dash/leap/global/exception/GlobalExceptionHandler.java
Labels: fix, refactor

#13 Fix #12 create modify date
  src/main/java/com/dash/leap/LeapApplication.java
  src/main/java/com/dash/leap/domain/chat/entity/ChatAnalysis.java
  src/main/java/com/dash/leap/domain/chat/entity/Message.java
  src/main/java/com/dash/leap/domain/diary/entity/DiaryAnalysis.java
  src/main/java/com/dash/leap/domain/mission/entity/MissionRecord.java
  src/main/java/com/dash/leap/domain/user/entity/User.java
  src/main/java/com/dash/leap/domain/user/service/UserService.java
Labels: fix

#15 Feature/#8/커뮤니티 게시글 작성
  src/main/java/com/dash/leap/domain/community/controller/PostController.java
  src/main/java/com/dash/leap/domain/community/dto/request/PostCreateRequest.java
  src/main/java/com/dash/leap/domain/community/dto/response/PostCreateResponse.java
  src/main/java/com/dash/leap/domain/community/entity/Post.java
  src/main/java/com/dash/leap/domain/community/repository/CommunityRepository.java
  src/main/java/com/dash/leap/domain/community/repository/PostRepository.java
  src/main/java/com/dash/leap/domain/community/service/PostService.java
Labels: feature

#18 Feature #14 user logic
  src/main/java/com/dash/leap/domain/user/controller/UserController.java
  src/main/java/com/dash/leap/domain/user/controller/docs/UserControllerDocs.java
  src/main/java/com/dash/leap/domain/user/dto/request/ChatbotSettingRequest.java
  src/main/java/com/dash/leap/domain/user/dto/request/UserRegisterRequest.java
  src/main/java/com/dash/leap/domain/user/dto/response/ChatbotSettingResponse.java
  src/main/java/com/dash/leap/domain/user/entity/User.java
  src/main/java/com/dash/leap/domain/user/exception/InvalidChatbotTypeException.java
  src/main/java/com/dash/leap/domain/user/exception/UserExceptionHandler.java
  src/main/java/com/dash/leap/domain/user/service/UserService.java
  src/main/java/com/dash/leap/global/auth/jwt/exception/PasswordMismatchException.java
  src/main/java/com/dash/leap/global/exception/GlobalExceptionHandler.java
  src/main/java/com/dash/leap/global/exception/NotFoundException.java
Labels: feature, refactor

#21 Fix #16 community create post
  src/main/java/com/dash/leap/domain/community/controller/PostController.java
  src/main/java/com/dash/leap/domain/community/dto/request/PostCreateRequest.java
  src/main/java/com/dash/leap/domain/community/dto/response/PostCreateResponse.java
  src/main/java/com/dash/leap/domain/community/service/PostService.java
Labels: fix

#20 feat #17 community update post
  src/main/java/com/dash/leap/domain/community/controller/PostController.java
  src/main/java/com/dash/leap/domain/community/dto/request/PostUpdateRequest.java
  src/main/java/com/dash/leap/domain/community/dto/response/PostUpdateResponse.java
  src/main/java/com/dash/leap/domain/community/entity/Post.java
  src/main/java/com/dash/leap/domain/community/service/PostService.java
Labels: feature

#24 Feat #5 community-delete-post
  src/main/java/com/dash/leap/domain/community/controller/PostController.java
  src/main/java/com/dash/leap/domain/community/controller/docs/CommunityControllerDocs.java
  src/main/java/com/dash/leap/domain/community/service/PostService.java
Labels: feature

#22 Feature #19 mission select area
  src/main/java/com/dash/leap/domain/mission/controller/MissionController.java
  src/main/java/com/dash/leap/domain/mission/controller/docs/MissionControllerDocs.java
  src/main/java/com/dash/leap/domain/mission/dto/response/MissionAreaResponse.java
  src/main/java/com/dash/leap/domain/mission/entity/Mission.java
  src/main/java/com/dash/leap/domain/mission/repository/MissionRecordRepository.java
  src/main/java/com/dash/leap/domain/mission/service/MissionService.java
  src/main/java/com/dash/leap/domain/user/controller/UserController.java
  src/main/java/com/dash/leap/domain/user/controller/docs/UserControllerDocs.java
  src/main/java/com/dash/leap/domain/user/dto/request/MissionAreaSettingRequest.java
  src/main/java/com/dash/leap/domain/user/dto/response/MissionAreaSettingResponse.java
  src/main/java/com/dash/leap/domain/user/entity/User.java
  src/main/java/com/dash/leap/domain/user/service/UserService.java
  src/main/java/com/dash/leap/global/exception/GlobalExceptionHandler.java
Labels: feature, refactor

#26 Refactor #25 커뮤니티 Swagger 문서 명세 개선
  src/main/java/com/dash/leap/domain/community/controller/docs/CommunityControllerDocs.java
Labels: refactor

#29 Feature #28 community create comment
  src/main/java/com/dash/leap/domain/community/controller/CommentController.java
  src/main/java/com/dash/leap/domain/community/controller/PostController.java
  src/main/java/com/dash/leap/domain/community/controller/docs/CommentControllerDocs.java
  src/main/java/com/dash/leap/domain/community/controller/docs/PostControllerDocs.java
  src/main/java/com/dash/leap/domain/community/dto/request/CommentCreateRequest.java
  src/main/java/com/dash/leap/domain/community/dto/response/CommentCreateResponse.java
  src/main/java/com/dash/leap/domain/community/entity/Comment.java
  src/main/java/com/dash/leap/domain/community/repository/CommentRepository.java
  src/main/java/com/dash/leap/domain/community/service/CommentService.java
Labels: feature, refactor

#31 Feature #30 add user deatils
  src/main/java/com/dash/leap/domain/mission/controller/MissionController.java
  src/main/java/com/dash/leap/domain/mission/controller/docs/MissionControllerDocs.java
  src/main/java/com/dash/leap/domain/mission/service/MissionService.java
  src/main/java/com/dash/leap/domain/user/controller/UserController.java
  src/main/java/com/dash/leap/domain/user/controller/docs/UserControllerDocs.java
  src/main/java/com/dash/leap/domain/user/service/UserService.java
  src/main/java/com/dash/leap/global/auth/jwt/service/JwtAuthenticationFilter.java
  src/main/java/com/dash/leap/global/auth/user/CustomUserDetails.java
  src/main/java/com/dash/leap/global/auth/user/CustomUserService.java
  src/main/java/com/dash/leap/global/config/security/SecurityConfig.java
Labels: feature, refactor

#34 Feature #23 chatbot
  src/main/java/com/dash/leap/domain/chat/controller/ChatMessageController.java
  src/main/java/com/dash/leap/domain/chat/controller/docs/ChatMessageControllerDocs.java
  src/main/java/com/dash/leap/domain/chat/dto/request/LeapyRequest.java
  src/main/java/com/dash/leap/domain/chat/dto/response/ChatResponse.java
  src/main/java/com/dash/leap/domain/chat/dto/response/LeapyResponse.java
  src/main/java/com/dash/leap/domain/chat/dto/response/MessageResponse.java
  src/main/java/com/dash/leap/domain/chat/entity/Chat.java
  src/main/java/com/dash/leap/domain/chat/entity/Message.java
  src/main/java/com/dash/leap/domain/chat/repository/ChatRepository.java
  src/main/java/com/dash/leap/domain/chat/repository/MessageRepository.java
  src/main/java/com/dash/leap/domain/chat/service/ChatMessageService.java
  src/main/java/com/dash/leap/domain/chat/service/prompt/SystemPromptFactory.java
  src/main/java/com/dash/leap/global/openai/client/OpenAIClient.java
  src/main/java/com/dash/leap/global/openai/config/OpenAIConfig.java
  src/main/java/com/dash/leap/global/openai/dto/MessageDto.java
  src/main/java/com/dash/leap/global/openai/dto/OpenAIRequest.java
  src/main/java/com/dash/leap/global/openai/dto/OpenAIResponse.java
Labels: feature

#37 Feature #32 회원가입 시 채팅방 자동 생성 로직
  src/main/java/com/dash/leap/domain/chat/service/ChatMessageService.java
  src/main/java/com/dash/leap/domain/user/service/UserService.java
Labels: feature

#38 Fix #36 cascade 설정으로 댓글 존재 시 게시글 삭제 오류 해결
  src/main/java/com/dash/leap/domain/community/entity/Post.java
Labels: fix

#40 Feat #39 커뮤니티 댓글 삭제
  src/main/java/com/dash/leap/domain/community/controller/CommentController.java
  src/main/java/com/dash/leap/domain/community/controller/docs/CommentControllerDocs.java
  src/main/java/com/dash/leap/domain/community/service/CommentService.java
Labels: feature

#42 Feat #41 커뮤니티 게시글 전체 목록 조회
  src/main/java/com/dash/leap/domain/community/controller/PostController.java
  src/main/java/com/dash/leap/domain/community/controller/docs/PostControllerDocs.java
  src/main/java/com/dash/leap/domain/community/dto/response/PostListAllResponse.java
  src/main/java/com/dash/leap/domain/community/repository/CommentRepository.java
  src/main/java/com/dash/leap/domain/community/repository/PostRepository.java
  src/main/java/com/dash/leap/domain/community/service/PostService.java
Labels: feature

#44 Feat #43 커뮤니티 게시글 상세 조회
  src/main/java/com/dash/leap/domain/community/controller/PostController.java
  src/main/java/com/dash/leap/domain/community/controller/docs/PostControllerDocs.java
  src/main/java/com/dash/leap/domain/community/dto/response/PostDetailResponse.java
  src/main/java/com/dash/leap/domain/community/repository/CommentRepository.java
  src/main/java/com/dash/leap/domain/community/service/PostService.java
Labels: feature

#48 Feature #47 LoginResponse에 userId 추가
  src/main/java/com/dash/leap/domain/user/dto/response/LoginResponse.java
  src/main/java/com/dash/leap/domain/user/service/UserService.java
Labels: feature

#51 Feat: 감정일기 작성
  src/main/java/com/dash/leap/domain/diary/controller/DiaryController.java
  src/main/java/com/dash/leap/domain/diary/controller/docs/DiaryControllerDocs.java
  src/main/java/com/dash/leap/domain/diary/dto/request/DiaryCreateRequest.java
  src/main/java/com/dash/leap/domain/diary/dto/response/DiaryCreateResponse.java
  src/main/java/com/dash/leap/domain/diary/entity/Diary.java
  src/main/java/com/dash/leap/domain/diary/repository/DiaryRepository.java
  src/main/java/com/dash/leap/domain/diary/service/DiaryService.java
Labels: feature

#55 Feat: 감정일기 월별 캘린더 조회
  src/main/java/com/dash/leap/domain/diary/controller/DiaryController.java
  src/main/java/com/dash/leap/domain/diary/controller/docs/DiaryControllerDocs.java
  src/main/java/com/dash/leap/domain/diary/dto/response/DiaryCalendarResponse.java
  src/main/java/com/dash/leap/domain/diary/entity/Diary.java
  src/main/java/com/dash/leap/domain/diary/repository/DiaryRepository.java
  src/main/java/com/dash/leap/domain/diary/service/DiaryService.java
Labels: feature

#58 Feature #49 미션 목록 조회, 수행일지 작성 및 조회
  src/main/java/com/dash/leap/domain/mission/controller/MissionController.java
  src/main/java/com/dash/leap/domain/mission/controller/docs/MissionControllerDocs.java
  src/main/java/com/dash/leap/domain/mission/dto/request/MissionRecordRequest.java
  src/main/java/com/dash/leap/domain/mission/dto/response/MissionRecordResponse.java
  src/main/java/com/dash/leap/domain/mission/dto/response/UserMissionListResponse.java
  src/main/java/com/dash/leap/domain/mission/dto/response/UserMissionResponse.java
  src/main/java/com/dash/leap/domain/mission/entity/MissionRecord.java
  src/main/java/com/dash/leap/domain/mission/entity/MissionStep.java
  src/main/java/com/dash/leap/domain/mission/exception/InvalidRecordRequestException.java
  src/main/java/com/dash/leap/domain/mission/exception/MissionExceptionHandler.java
  src/main/java/com/dash/leap/domain/mission/repository/MissionRecordRepository.java
  src/main/java/com/dash/leap/domain/mission/service/MissionService.java
Labels: feature

#59 Refactor #56 diary monthly calendar
  src/main/java/com/dash/leap/domain/diary/dto/response/DiaryDetailResponse.java
  src/main/java/com/dash/leap/domain/diary/entity/DiaryAnalysis.java
  src/main/java/com/dash/leap/domain/diary/repository/DiaryRepository.java
  src/main/java/com/dash/leap/domain/diary/service/DiaryService.java
Labels: feature, refactor

#61 Fix #57 assign missions
  src/main/java/com/dash/leap/domain/mission/controller/MissionController.java
  src/main/java/com/dash/leap/domain/mission/controller/docs/MissionControllerDocs.java
  src/main/java/com/dash/leap/domain/mission/dto/request/MissionAreaSettingRequest.java
  src/main/java/com/dash/leap/domain/mission/dto/response/MissionAreaSettingResponse.java
  src/main/java/com/dash/leap/domain/mission/exception/InvalidMissionAreaChangeException.java
  src/main/java/com/dash/leap/domain/mission/exception/MissionExceptionHandler.java
  src/main/java/com/dash/leap/domain/mission/repository/MissionRecordRepository.java
  src/main/java/com/dash/leap/domain/mission/repository/MissionRepository.java
  src/main/java/com/dash/leap/domain/mission/service/MissionService.java
  src/main/java/com/dash/leap/domain/user/controller/UserController.java
  src/main/java/com/dash/leap/domain/user/controller/docs/UserControllerDocs.java
  src/main/java/com/dash/leap/domain/user/exception/UserExceptionHandler.java
  src/main/java/com/dash/leap/domain/user/service/UserService.java
Labels: fix

#62 Feature #49 미션 상세 조회
  src/main/java/com/dash/leap/domain/mission/controller/MissionController.java
  src/main/java/com/dash/leap/domain/mission/controller/docs/MissionControllerDocs.java
  src/main/java/com/dash/leap/domain/mission/dto/response/MissionDetailResponse.java
  src/main/java/com/dash/leap/domain/mission/dto/response/MissionStepResponse.java
  src/main/java/com/dash/leap/domain/mission/exception/ForbiddenAccessMissionDetailException.java
  src/main/java/com/dash/leap/domain/mission/exception/MissionExceptionHandler.java
  src/main/java/com/dash/leap/domain/mission/repository/MissionRecordRepository.java
  src/main/java/com/dash/leap/domain/mission/repository/MissionStepRepository.java
  src/main/java/com/dash/leap/domain/mission/service/MissionService.java
Labels: feature

#63 Fix #60 챗봇 설정 관련 문제 수정
  src/main/java/com/dash/leap/domain/user/dto/request/ChatbotSettingRequest.java
  src/main/java/com/dash/leap/domain/user/entity/User.java
  src/main/java/com/dash/leap/domain/user/exception/InvalidChatbotException.java
  src/main/java/com/dash/leap/domain/user/exception/UserExceptionHandler.java
  src/main/java/com/dash/leap/domain/user/service/UserService.java
Labels: fix
